"""10d

Revision ID: 03eb3852a13c
Revises: 29c602b6bd22
Create Date: 2017-06-27 22:46:44.551983

"""

# revision identifiers, used by Alembic.
revision = '03eb3852a13c'
down_revision = '29c602b6bd22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
