"""11f

Revision ID: 2f5bf929bc3c
Revises: a7188a34717c
Create Date: 2017-07-10 00:26:04.362254

"""

# revision identifiers, used by Alembic.
revision = '2f5bf929bc3c'
down_revision = 'a7188a34717c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
