"""12a

Revision ID: 322449851b24
Revises: 2f5bf929bc3c
Create Date: 2017-07-10 23:37:43.620348

"""

# revision identifiers, used by Alembic.
revision = '322449851b24'
down_revision = '2f5bf929bc3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
