"""now

Revision ID: 76bcbd1efb72
Revises: 64c8a08333ab
Create Date: 2017-05-18 21:40:49.345294

"""

# revision identifiers, used by Alembic.
revision = '76bcbd1efb72'
down_revision = '64c8a08333ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
