"""11a

Revision ID: a7188a34717c
Revises: 4cb181cd85d5
Create Date: 2017-06-28 00:43:19.154414

"""

# revision identifiers, used by Alembic.
revision = 'a7188a34717c'
down_revision = '4cb181cd85d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
