"""9

Revision ID: b9ce9f9c4007
Revises: 3f4b6c8b4261
Create Date: 2017-05-24 21:03:22.534974

"""

# revision identifiers, used by Alembic.
revision = 'b9ce9f9c4007'
down_revision = '3f4b6c8b4261'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
